//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PamagitMenzPoxitiliIDerjatVZalojnikax
{
    using System;
    using System.Collections.Generic;
    
    public partial class Comments
    {
        public int ID { get; set; }
        public string Message { get; set; }
        public int MasterID { get; set; }
        public int RequestID { get; set; }
    
        public virtual Request Request { get; set; }
        public virtual Users Users { get; set; }
    }
}
